#ifndef BIO_ERRORHANDLE_H_INCLUDED
#define BIO_ERRORHANDLE_H_INCLUDED

#include <openssl/bio.h>

#define ERROR_FUNCTION_ADDRESS_SPACE 16
#define ERROR_TYPE_ADDRESS_SPACE 8
#define ERROR_CODE_ADDRESS_SPACE 0

#define ERROR_FUNCTION_ADDRESS_MASK 0xFFFF0000
#define ERROR_TYPE_MASK 0xFF00
#define ERROR_CODE_MASK 0xFF

#define ERROR_FUNCTION_ADDRESS(x) (x << ERROR_FUNCTION_ADDRESS_SPACE)
#define ERROR_TYPE_ADDRESS(x) (x << ERROR_TYPE_ADDRESS_SPACE)
#define ERROR_CODE_ADDRESS(x) (x << ERROR_CODE_ADDRESS_SPACE)

#define ERROR_FULL_ADDRESS(function, type, code) (function ^ type ^ code)

#define ERROR_FUNCTION_NONE ERROR_FUNCTION_ADDRESS(0)

#define ERROR_TYPE_INPUT_NULL ERROR_TYPE_ADDRESS(0)
#define ERROR_TYPE_MEMORY_ALLOCATION ERROR_TYPE_ADDRESS(1)
#define ERROR_TYPE_BIO ERROR_TYPE_ADDRESS(2)
#define ERROR_TYPE_OPENSSL ERROR_TYPE_ADDRESS(255)

#define ERROR_NO_ERROR ERROR_FULL_ADDRESS(ERROR_FUNCTION_NONE, 0, 0)
#define ERROR_INTERRUPT ERROR_FULL_ADDRESS(ERROR_FUNCTION_NONE, 0, 1)

#define ERROR_STRING_LEN 128

int writeErrorCode(int code);

int getErrorCode();

char * getErrorString(int code);

BIO ** getErrorStack();

#endif // BIO_ERRORHANDLE_H_INCLUDED
