#ifndef EVP_ASYNC_DIGEST_H_INCLUDED
#define EVP_ASYNC_DIGEST_H_INCLUDED

#define ERROR_ASYNC_DIGEST_ADDRESS ERROR_FUNCTION_ADDRESS(7)

void * async_digest(void * arg);

#endif // EVP_ASYNC_DIGEST_H_INCLUDED
