#ifndef EVP_ASYNC_DERIVEKEY_H_INCLUDED
#define EVP_ASYNC_DERIVEKEY_H_INCLUDED

#define ERROR_ASYNC_DERIVE_KEY_ADDRESS ERROR_FUNCTION_ADDRESS(3)

void * async_derive_key(void * arg);

#endif // EVP_ASYNC_DERIVEKEY_H_INCLUDED
