#ifndef EVP_ASYNC_ENCRYPTDECRYPT_H_INCLUDED
#define EVP_ASYNC_ENCRYPTDECRYPT_H_INCLUDED

#define ERROR_ASYNC_ENCRYPT_DECRYPT_ADDRESS ERROR_FUNCTION_ADDRESS(5)

void * async_encrypt(void * arg);

void * async_decrypt(void * arg);

#endif // EVP_ASYNC_ENCRYPTDECRYPT_H_INCLUDED
