#ifndef PKEY_ASYNC_AGREMEENT_H_INCLUDED
#define PKEY_ASYNC_AGREMEENT_H_INCLUDED

#define ERROR_ASYNC_AGREMEENT_ADDRESS ERROR_FUNCTION_ADDRESS(29)

void * async_agremeent(void * arg);

#endif // PKEY_ASYNC_SIGN_H_INCLUDED
